### ISSUE TITLE
Fix bash/PlutusTx scripts for the E2E Plonk test

### ISSUE THREAD

**Issue by vlasin** [zkFold/zkfold-cardano#16]
- [x] Resolve possible PlutusV3 bug or error in our PlutusTx code.
- [x] An "always succeeds" version of minting script should mint.
- [x] Minting with "plonk verifier" should work.
- [x] Burning transaction should work.
- [x] Update documentation.

**Comment by ajuggler** [comment]
Got useful feedback pointing out that in PlutusV3 all validators should have type signature `BuiltinData -> BuiltinUnit`.  Had to modify PlutusTx scripts accordingly.  Now able to mint with trivial "always succeeds" version of the script.

**Comment by ajuggler** [comment]
Waiting for comments on pull-request.
